-- CreateEnum
CREATE TYPE "FlagType" AS ENUM ('STRONG_ANSWER', 'GOOD_INSIGHT', 'HINT_NEEDED', 'MISSED_EDGE_CASE', 'OPTIMIZATION_FOUND', 'COMMUNICATION_ISSUE');

-- AlterTable
ALTER TABLE "InterviewEvent" ADD COLUMN     "flagType" "FlagType";
